---

- name: Install Update CRON
  template:
    src="epel-mirror.j2"
    dest="{{ mirror_cron_dir }}/epel-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="EPEL"
    minute="{{ epel_mirror_cron_minute }}"
    hour="{{ epel_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/epel-mirror"
    disabled="{{ epel_mirror_cron_disabled }}"
