---

- name: Install Mirror Manager Config
  template:
    src="report_mirror-epel.conf.j2"
    dest="{{ mirror_unix_home }}/report_mirror-epel.conf"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0600

- name: Install Update CRON
  template:
    src="epel-mirror.j2"
    dest="{{ mirror_cron_dir }}/epel-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="EPEL"
    minute="{{ epel_mirror_cron_minute }}"
    hour="{{ epel_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/epel-mirror >/dev/null 2>&1"
    disabled="{{ epel_mirror_cron_disabled }}"

- stat:
    path="{{ mirror_timestamp_dir }}/epel"
  register: tsfile

- name: Seed Timestamp File
  copy:
    content="0"
    dest="{{ mirror_timestamp_dir }}/epel"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0644
  when: not tsfile.stat.exists
